src/menus/urls.py

from django.conf.urls import include, url

from .views import (
	ItemsListView,
	ItemsDetailView,
	ItemsUpdateView,
	ItemsCreateView,

)

urlpatterns = [

    url(r'^create$', ItemsCreateView.as_view(),  name='create'),
    # url(r'^(?P<pk>\d+)/edit$', ItemsUpdateView.as_view(), name='edit'),
    # url(r'^(?P<pk>\d+)$', ItemsDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)$', ItemsUpdateView.as_view(), name='detail'),
    url(r'^$', ItemsListView.as_view(), name='list'),
]

src/muypicky/urls.py
"""MuyPicky URL Configuration

The 'urlpatterns' list routes URLs to views. for more details:
http://docs.djangoproject.com/en/1.11/topics/http/urls/

example:
function views
1. add import: from my_app import views
2. add a url to urlpatterns: url(r'^$', views.home, name='home')

class-based views
1. add an import: from other_app.views import Home
2. add a url to urlpatterns: url(r'^$', Home.as_view(), name='home')

including another URLconf
1. import the include() function: from django.conf.urls import url, include
2. add a url to urlpatterns: url(r'^blog/', include('blog.urls'))
"""

from django.contrib.auth.views import LoginView, LogoutView



from django.conf.urls import include, url
from django.contrib import admin
#from restaurants.views import HomeView 
from django.views.generic.base import TemplateView
from restaurants.views import (
	# restaurant_listview,
	RestaurantsListView,
	# MexicanRestaurantsListView,
	# AsianRestaurantsListView,
	SearchRestaurantsListView,
	RestaurantsDetailView,
	restaurant_createview,
	RestaurantCreateView,
    restaurant_FBV_createview
)

from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
from menus.views import HomeView

urlpatterns = [
    # Examples:
    # url(r'^$', 'muypicky.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    #url(r'^$', HomeView.as_view()), #this need to be used like this because it contains context in views.py
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', HomeView.as_view(), name='home'),
    #url(r'^restaurants$', restaurant_listview),
    
    #included from restaurants/urls.py
    #url(r'^restaurants/$', RestaurantsListView.as_view(), name='restaurants'),
    
    #url(r'^restaurants/create$', restaurant_createview),
    url(r'^restaurants/create_FBV$' , restaurant_FBV_createview),

    #included from restaurants/urls.py
    #url(r'^restaurants/create$', RestaurantCreateView.as_view(),  name='restaurants-create'),
    
    # url(r'^restaurants/(?P<slug>\w+)$', SearchRestaurantsListView.as_view()),
    #url(r'^restaurants/(?P<pk>\w+)$', RestaurantsDetailView.as_view()),
    # url(r'^restaurants/(?P<rest_id>\w+)$', RestaurantsDetailView.as_view()),

    #included from restaurants/urls.py
    #url(r'^restaurants/(?P<slug>[\w-]+)$', RestaurantsDetailView.as_view(), name='restaurant-detail'),

    #url(r'^restaurants/mexican$', MexicanRestaurantsListView.as_view()),
    #url(r'^restaurants/asian$', AsianRestaurantsListView.as_view()),
    
    # url(r'^about$', AboutView.as_view()),
    # # url(r'^contact/(?P<Id>\d+)$', ContactView.as_view()),
    # url(r'^contact$', ContactView.as_view())
    url(r'^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact$', TemplateView.as_view(template_name='contact.html'), name='contact'),

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
]

src/menus/models.py
from django.conf import settings
from django.db import models
from restaurants.models import RestaurantLocation
from django.core.urlresolvers import reverse

class Items(models.Model):
	# association
	user 		= models.ForeignKey(settings.AUTH_USER_MODEL)
	restaurant	= models.ForeignKey(RestaurantLocation)
	# item stuff
	name 		= models.CharField(max_length=120)
	contents	= models.TextField(help_text='Seperate each by comma')
	excludes	= models.TextField(blank=True, null=True, help_text='Seperate each by comma')
	public 		= models.BooleanField(default=True)
	timestamp	= models.DateTimeField(auto_now_add=True)
	updated 	= models.DateTimeField(auto_now=True)

	#chaneg the Itemobject to it's name
	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('menus:detail', kwargs={'pk': self.pk})

	class Meta:
		ordering = ['-updated','-timestamp'] # Item.objects.all() 
		#-updated --> return the first updated item, 
		#updated  --> return the last updated item

	def get_contents(self):
		return self.contents.split(",")

	def get_excludes(self):
		return self.excludes.split(",")


src/menus/forms.py
from django import forms 
from .models import Items
from restaurants.models import RestaurantLocation

class ItemsForm(forms.ModelForm):
	class Meta:
		model = Items
		fields = [
			'restaurant',
			'name',
			'contents',
			'excludes',
			'public'
		]

	def __init__(self, user=None, *args, **kwargs):
		print(user)
		# print(kwargs.pop('instance'))
		print(kwargs)
		super(ItemsForm, self).__init__(*args, **kwargs)
		self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)#.exclude(items__isnull=False)

src/menus/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView
# Create your views here.
from .models import Items
from .forms import ItemsForm
from django.contrib.auth.mixins import LoginRequiredMixin 

class HomeView(LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return render(request, "home.thml", {})
		else:
			user = self.request.user
			is_following_user_id = [x.user.id for x in user.is_following.all()] 
			qs = Items.objects.filter(user__id__in = is_following_user_id, public=True).order_by("-updated")[:10] #first 3 latest

			return render(request, "menus/home-feed.html", {'object_list':qs})

class ItemsListView(LoginRequiredMixin, ListView):
	def get_queryset(self):
		return Items.objects.filter(user=self.request.user)

class ItemsDetailView(LoginRequiredMixin, DetailView):
	def get_queryset(self):
		return Items.objects.filter(user=self.request.user)

class ItemsCreateView(LoginRequiredMixin, CreateView):
	template_name = 'form.html'
	form_class = ItemsForm

	def get_queryset(self):
		return Items.objects.filter(user=self.request.user)

	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.user = self.request.user #anonymousUser
		#instance.save()
		return super(ItemsCreateView, self).form_valid(form)

	def get_context_data(self, *args, **kwargs):
		context = super(ItemsCreateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Create Item'
		return context

	#get args that passed into form_class
	def get_form_kwargs(self):
		kwargs = super(ItemsCreateView, self).get_form_kwargs()
		kwargs['user']=self.request.user
		# kwargs['instance']=Items.objects.filter(user=self.request.user).first()
		return kwargs 

class ItemsUpdateView(LoginRequiredMixin, UpdateView):
	template_name = 'menus/detail-update.html'
	form_class = ItemsForm

	def get_queryset(self):
		return Items.objects.filter(user=self.request.user)

	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.user = self.request.user #anonymousUser
		#instance.save()
		return super(ItemsUpdateView, self).form_valid(form)

	def get_context_data(self, *args, **kwargs):
		context = super(ItemsUpdateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Update Item'
		return context

	def get_form_kwargs(self):
		kwargs = super(ItemsUpdateView, self).get_form_kwargs()
		kwargs['user']=self.request.user
		# kwargs['instance']=Items.objects.filter(user=self.request.user).first()
		return kwargs 

src/menus/templates/menus/detail-update.html
{% extends "base.html" %}
{% block head_title %} {{ form.instance.name }} | Menu Items | {{block.super}}{% endblock head_title %}

{% block content %}
<h1>{{form.instance.name}}</h1>   
<P>Location: {{form.instance.restaurant.name}}</p> 
			{% if form.instance.contents %}
			Contents
			<ul>
				{% for item in form.instance.get_contents %}
				<li>{{ item }}</li>
				{% endfor %}
			</ul>
			{% endif %}
			{% if form.instance.excludes %}
			Excludes
			<ul>
				{% for item in form.instance.get_excludes %}
				<li>{{ item }}</li>
				{% endfor %}
			</ul>
			{% endif %}

<hr/>
<h3>Make Changes</h3>
<!-- form here is the context comming through -->
{% include 'snippets/form-snippet.html' with form=form %}
{% endblock content %}

src/menus/templates/menus/home-feed.html
{% extends "base.html" %}
{% block content %}

<div class='row'>
<div class='col-sm-6 text-center col-sm-offset-3'>
<h1>{{ request.user }}'s Following Feed</h1> 
<h4><a href='{% url "profile:detail" username=request.user %}'>>My Profile</a></h4>

{% if object_list %}
	{% for obj in object_list %}

		<div class='thumbnail'>
			<h3><a href='{% url "profile:detail" username=obj.user %}'>{{obj.user }}</a></h3> 	
			<h4><b>{{obj.name }}</b></h4> 	
			<p><a href='{% url "profile:detail" username=obj.user %}?q={{obj.restaurant.name}}'>{{obj.restaurant.name}}</a> | <a href='{% url "profile:detail" username=obj.user %}?q={{obj.restaurant.location}}'>{{obj.restaurant.location}}</a> | <a href='{% url "profile:detail" username=obj.user %}?q={{obj.restaurant.category}}'>{{obj.restaurant.category}}</a></p>
			<p>
				<b>{{obj.name }}:</b>
					{% if obj.contents %} With 
						{% for item in obj.get_contents %}
						<a href='{% url "profile:detail" username=obj.user %}?q={{item}}'>{{item}}</a>
						{% endfor %}
					{% endif %}
			</p>
		</div>

	{% endfor %}
{% else %}
<p class='lead'> No Items Found</p>
{% endif %}
</div>
</div>
{% endblock content %}

src/menus/templates/menus/items_detail.html
{% extends "base.html" %}
{% block head_title %}Menu Items || {{block.super}}{% endblock head_title %}

{% block content %}
<h1>{{object.name}}</h1>   
<P>Location: {{object.restaurant.name}}</p> 
			{% if object.contents %}
			Contents
			<ul>
				{% for item in object.get_contents %}
				<li>{{ item }}</li>
				{% endfor %}
			</ul>
			{% endif %}
			{% if object.excludes %}
			Excludes
			<ul>
				{% for item in object.get_excludes %}
				<li>{{ item }}</li>
				{% endfor %}
			</ul>
			{% endif %}

{% endblock content %}

src/menus/templates/menus/items_list.html
{% extends "base.html" %}
{% block head_title %}Menu Items || {{block.super}}{% endblock head_title %}

{% block content %}
<h1>Menu Items <small><a href='{% url "menus:create" %}'>Add</a></small></h1>   

<ul>
	{% if object_list %}
	{% for obj in object_list %}
		<li>
			<a href='{{ obj.get_absolute_url }}'/>{{obj.name}}</a><br/>
			{% if obj.contents %}
			Contents
			<ul>
				{% for item in obj.get_contents %}
				<li>{{ item }}</li>
				{% endfor %}
			</ul>
			{% endif %}
			{% if obj.excludes %}
			Excludes
			<ul>
				{% for item in obj.get_excludes %}
				<li>{{ item }}</li>
				{% endfor %}
			</ul>
			{% endif %}
		</li>
		{% empty %}
		<a href='{% url "menu:create" %}'>Add New Item</a>
	{% endfor %}
	{% endif %}
</ul>
{% endblock content %}